@startuml
skinparam actorStyle awesome

actor Volontario as volunteer
box "View" #LemonChiffon
entity "Web Server" as webServer
participant DatePickerViewController as dpController
end box
box "Controller" #lightgreen

participant VolunteerAvailablilityController as vaController
end box
box "Model" #sandybrown
participant VolunteersAvailabilityService as vaService

end box

box "Persistence" #mediumpurple
participant MonthColletionStateAdapter as mcsAdapter
participant JpaVolunteerAvailableDateRepositoryAdapter as jpadRepositoryAdapter
participant MonthColletionStateRepository as mcsRepository
participant VolunteerAvailableDateRepository as vadRepository
database Database as db
end box

volunteer --> webServer : "GET /date-picker"
webServer -> dpController : "showDatePicker()"
dpController -> webServer : "date-picker"
webServer --> volunteer : "200 OK date-picker.html"
volunteer --> webServer : "GET /is-enabled"
webServer -> vaController : "isAvailablityEnabled()"
vaController -> vaService : "isAvailabilityEnabled()"
vaService -> mcsAdapter : "isVolunteerAvailabilityOpen()"
mcsAdapter -> mcsRepository : "findByMonthAndYear()"
mcsRepository --> db : "query"
db --> mcsRepository : "response"
mcsRepository --> mcsAdapter
mcsAdapter --> vaService
vaService --> vaController : "raccolta disponibilitá abilitata"
vaController --> webServer : "true"
webServer --> volunteer : "200 OK true"

volunteer --> webServer : "POST /update-own lista-date (JSON)"
webServer --> vaController : "updateOwnAvailablity()"
vaController -> vaService : "updateAvailability()"
vaService -> jpadRepositoryAdapter : "save()"
jpadRepositoryAdapter --> vadRepository : "~save()"
vadRepository --> db : "scrittura su DB"
@enduml
