spring:
  datasource:
    url: jdbc:mysql://localhost:3306/destinazioni
    username: destinazioni
    password: destinazioni
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  test:
    database:
      replace: none
    
  liquibase:
    enabled: false