@startuml

set separator none

package "adapters.jpa" #cc77ff {
	package "adapter" #ccbbff
	package "entity" #ccbbff
	package "repository" #ccbbff
}

package "application" #0088ff {

  package "exception" #00bbff {
		package "codes" #00eeff
    package "usecases" #00eeff
    package "base" #00eeff
	}

	package "port" #00bbff {
		package "in" #00eeff {
			package "areaofinterest" #bcffff
			package "blockeddates" #bcffff
			package "booking" #bcffff
			package "configuration" #bcffff
			package "location" #bcffff
			package "login" #bcffff
			package "user" #bcffff
			package "visit" #bcffff
			package "visitplan" #bcffff
			package "visittype" #bcffff
			package "volunteer" #bcffff
		}

		package "out" #00eeff
	}

    package "services" #00bbff

    package "rest" #00bbff {
		  package "advice" #00eeff {
        package "strategy" #bcffff
      }
		  package "controller" #00eeff

      package "util" #00eeff {
        package "mapper" #bcffff
      }
	}

  package "util " #00bbff

}

package "config" #fbfc93

package "domain" #ffbb4d {
	package "dto" #ffd179
	package "model" #ffd179 {
		package "enums" #ffdfb0
	}
}

package "ui" #66ff66 {
	package "view.controller" #ccffcc
}
